services:
  mysql:
    image: bitnami/mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=db_mscustomer
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
