services:
  mysql:
    image: bitnami/mysql:latest
    ports:
      - '3308:3308'
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=db_mscalculate
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
